((
  top (
    (module_name picorv32)
    (path        picorv32.v)
    (instantiates ())
    (parameters (
      (ENABLE_COUNTERS      (Int 1))
      (ENABLE_COUNTERS64    (Int 1))
      (ENABLE_REGS_16_31    (Int 1))
      (ENABLE_REGS_DUALPORT (Int 1))
      (TWO_STAGE_SHIFT      (Int 1))
      (BARREL_SHIFTER       (Int 0))
      (TWO_CYCLE_COMPARE    (Int 0))
      (TWO_CYCLE_ALU        (Int 0))
      (COMPRESSED_ISA       (Int 0))
      (CATCH_MISALIGN       (Int 1))
      (CATCH_ILLINSN        (Int 1))
      (ENABLE_PCPI          (Int 0))
      (ENABLE_MUL           (Int 0))
      (ENABLE_FAST_MUL      (Int 0))
      (ENABLE_DIV           (Int 0))
      (ENABLE_IRQ           (Int 0))
      (ENABLE_IRQ_QREGS     (Int 1))
      (ENABLE_IRQ_TIMER     (Int 1))
      (ENABLE_TRACE         (Int 0))
      (REGS_INIT_ZERO       (Int 0))
      (MASKED_IRQ           (Int 0x0000_0000))
      (LATCHED_IRQ          (Int 0xffff_ffff))
      (PROGADDR_RESET       (Int 0x0000_0000))
      (PROGADDR_IRQ         (Int 0x0000_0010))
      (STACKADDR            (Int 0xffff_ffff))
      (LATCHED_MEM_RDATA    (Int 0)))))))
